In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([48, 45, 34, 12, 36, 47, 30, 20, 36, 47])

In [5]:
random_int_array.size

10

In [6]:
random_int_array.dtype


dtype('int32')

In [7]:
random_int_array.ndim

1

In [12]:
random_int_mtr = np.random.randint(10, 100, size=(2,5))

In [13]:
random_int_mtr

array([[40, 20, 12, 82, 49],
       [58, 86, 31, 32, 62]])

In [14]:
random_int_mtr.shape

(2, 5)

In [15]:
#1
np.mean(random_int_array)

35.2

In [16]:
#2
a = np.random.randint(1, 100, size=(3,3))
b = np.random.randint(1, 100, size=(3,3))
ab=a+b

In [17]:
ab

array([[ 12, 150,  61],
       [ 31,  60, 121],
       [ 97, 126, 110]])

In [18]:
np.mean(ab)

85.33333333333333

In [27]:
#3
arr=np.random.randint(1, 100, size=(20))
arr

array([ 7,  2, 83, 87,  5, 16, 84, 88, 13, 40, 15, 28, 67, 55, 23, 72, 28,
       81, 79, 53])

In [28]:
filter_arr=arr[arr>50]
filter_arr

array([83, 87, 84, 88, 67, 55, 72, 81, 79, 53])

In [35]:
arr1 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10])
np.random.shuffle(arr1)
arr1

array([ 7,  2,  1,  4,  9,  6,  3,  5,  8, 10])